
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncodding=utf-8&true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.ywy.mybatisdemo.entity
server:
  port: 8081
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql