
spring:
  application:
    name: mydemo
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncodding=utf-8&true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.ywy.mybatisdemo.entity
server:
  port: 8081
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
dubbo:
  application:
    name: demo_provider
  registry:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.ywy.mybatisdemo.service


